### ISSUE TITLE
check the api weekly

### ISSUE THREAD

**Issue by chnuessli** [wc-guide/wc-guide-data#23]

**Comment by chnuessli** [comment]
the api seems to be working fine now. i saw a problem that all the json files were empty and maybe need to keep track of this. i had this problem with defis a long time ago, but within an hour the problem there was solved. i need to ask samuel if there's a locl databse as backup.

**Comment by Sonnenschauer** [comment]
Thanks for checking! Maybe it's even possible to check the incoming data first if it is NULL (empty) and if so, don't update?

**Comment by chnuessli** [comment]
The file is never NULL/Empty, that's the "problem"
________________________________
Von: Adriano Fattizzo ***@***.***>
Gesendet: Mittwoch, 4. August 2021 05:24
An: wc-guide/wc-guide-data ***@***.***>
Cc: Christian Nüssli ***@***.***>; Assign ***@***.***>
Betreff: Re: [wc-guide/wc-guide-data] check the api weekly (#23)


Thanks for checking! Maybe it's even possible to check the incoming data first if it is NULL (empty) and if so, don't update?

**Comment by chnuessli** [comment]
seems to be working on a reliable base. some bumps can happen.
